# Production SQL Server Load Test Configuration

database:
  type: sqlserver
  host: 10.54.41.247
  port: 1433
  username: fiyuu_banned_lines
  password: &45FjGA+ml1nPE)xO?9$
  database: TFICarrierTrackNEW
  ssl_mode: disable
  
  max_open_conns: 10000
  max_idle_conns: 100
  conn_max_lifetime: 1h
  conn_max_idle_time: 10m

test:
  duration: 10m
  concurrent_users: 10000
  ramp_up_time: 1m
  think_time: 500ms
  
  queries:
    - name: "select_system_info"
      sql: "SELECT @@VERSION as version, GETDATE() as current_time, DB_NAME() as database_name"
      weight: 30
      type: "select"
      
    - name: "select_tables"
      sql: "SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
      weight: 25
      type: "select"
      
    - name: "select_table_count"
      sql: "SELECT COUNT(*) as table_count FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
      weight: 20
      type: "select"
      
    - name: "select_connections"
      sql: "SELECT COUNT(*) as connection_count FROM sys.dm_exec_connections"
      weight: 15
      type: "select"
      
    - name: "select_sessions"
      sql: "SELECT COUNT(*) as session_count FROM sys.dm_exec_sessions WHERE is_user_process = 1"
      weight: 10
      type: "select"

metrics:
  enabled: true
  interval: 5s
  output_file: "production_metrics.json"
  
  prometheus:
    enabled: true
    port: 8080
    path: "/metrics"
