# SQL Server Load Test Configuration

database:
  type: mssql
  host: localhost
  port: 1433
  username: sa
  password: password
  database: master
  ssl_mode: disable
  
  max_open_conns: 10000
  max_idle_conns: 100
  conn_max_lifetime: 1h
  conn_max_idle_time: 10m

test:
  duration: 10m
  concurrent_users: 10000
  ramp_up_time: 1m
  think_time: 500ms
  
  queries:
    - name: "select_system_info"
      sql: "SELECT @@VERSION as version, GETDATE() as current_time"
      weight: 30
      type: "select"
      
    - name: "select_databases"
      sql: "SELECT name, database_id, create_date FROM sys.databases WHERE database_id > 4"
      weight: 25
      type: "select"
      
    - name: "select_tables"
      sql: "SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
      weight: 20
      type: "select"
      
    - name: "select_connections"
      sql: "SELECT COUNT(*) as connection_count FROM sys.dm_exec_connections"
      weight: 15
      type: "select"
      
    - name: "select_sessions"
      sql: "SELECT COUNT(*) as session_count FROM sys.dm_exec_sessions WHERE is_user_process = 1"
      weight: 10
      type: "select"

metrics:
  enabled: true
  interval: 5s
  output_file: "sqlserver_metrics.json"
  
  prometheus:
    enabled: true
    port: 8080
    path: "/metrics"
