# Test Configuration - Sadece SELECT @@VERSION testi

database:
  type: sqlserver
  host: 10.54.41.247
  port: 1433
  username: fiyuu_banned_lines
  password: "&45FjGA+ml1nPE)xO?9$"
  database: TFICarrierTrackNEW
  ssl_mode: disable
  
  # Test için yüksek connection pool ayarları
  max_open_conns: 15000      # 10k user + 5k buffer
  max_idle_conns: 10000      # Daha fazla idle connection
  conn_max_lifetime: 10m     # Daha kısa lifetime
  conn_max_idle_time: 2m     # Daha kısa idle time
  query_timeout: 30s

test:
  duration: 10m               # 10 dakika test süresi
  concurrent_users: 10000     # 10,000 concurrent user
  ramp_up_time: 30s           # 30 saniyede 10k kullanıcıya çık
  think_time: 1s              # Normal think time
  
  # Sadece SELECT @@VERSION testi
  queries:
    - name: "select_version_only"
      sql: "SELECT @@VERSION as version"
      weight: 100
      type: "select"

metrics:
  enabled: true
  interval: 10s
  output_file: "test_metrics.json"
  
  prometheus:
    enabled: true
    port: 8080
    path: "/metrics"
