# Test Configuration - Sadece SELECT @@VERSION testi

database:
  type: sqlserver
  host: ktdblsn.fiyuu.local
  port: 1433
  username: fiyuu_banned_lines
  password: "&45FjGA+ml1nPE)xO?9$"
  database: TFICarrierTrackNEW
  ssl_mode: disable
  
  # Test için yüksek connection pool ayarları
  max_open_conns: 20000      # 15k user + 5k buffer
  max_idle_conns: 15000      # Daha fazla idle connection
  conn_max_lifetime: 5m      # Daha kısa lifetime
  conn_max_idle_time: 1m     # Daha kısa idle time
  query_timeout: 30s

test:
  duration: 10m               # 10 dakika test süresi
  concurrent_users: 100     # 15,000 concurrent user
  ramp_up_time: 30s           # 30 saniyede 15k kullanıcıya çık
  think_time: 1s              # Normal think time
  
  # Production query'leri ile test
  queries:
    - name: "select_version"
      sql: "SELECT 1"
      weight: 20
      type: "select"

metrics:
  enabled: true
  interval: 10s
  output_file: "logs/test_metrics.json"
  
  prometheus:
    enabled: true
    port: 8080
    path: "/metrics"
